# Source: cluster-api-aws/templates/cluster.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: bc60f7b3-0d8e-46b7-a1ba-39b379755549
  namespace: bc60f7b3-0d8e-46b7-a1ba-39b379755549
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: bc60f7b3-0d8e-46b7-a1ba-39b379755549
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "bc60f7b3-0d8e-46b7-a1ba-39b379755549-control-plane"
