# Source: cluster-autoscaler/templates/rbac-for-mgmt-cluster-access.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
  namespace: bc60f7b3-0d8e-46b7-a1ba-39b379755549
rules:
  - apiGroups:
    - cluster.x-k8s.io
    resources:
    - machinedeployments
    - machinedeployments/scale
    - machines
    - machinesets
    verbs:
    - get
    - list
    - update
    - watch
